### ISSUE TITLE
Dev server mounts not working on Unix

### ISSUE THREAD

**Issue by tommywalkie** [tommywalkie/ant-design-svelte#2]
We currently have a Snowpack/Skypack dev server suited for Svelte and React components which work well and already has sort of type safety. The cool feature is we can showcase our Svelte components with actual Ant Design of React side-by-side comparison

![image](https://user-images.githubusercontent.com/16148332/100616848-fc98bf80-3319-11eb-9be2-050cd9baf0ef.png)

The one caveat we have is Snowpack production builds are not suited for production, ideally we would like to release our showcase dev server on Github Pages or Vercel, everything is set up, we actually just need a proper production build process.

**Comment by tommywalkie** [comment]
A user reached me and reported issues regarding the dev server startup with the following logs (probably on a Linux or MacOS environment)

```
[snowpack] [404] /_dist_/components/Grid.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Grid.svx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.js
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Grid.svx
[snowpack] [404] /_dist_/components/Typography.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Typography.svx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.js
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Typography.svx
[snowpack] [404] /_dist_/components/Card.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/_dist_/components/Card.svx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.js
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/src/components/Card.svx
[snowpack] [404] /antd/Typography.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.js
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.mjs
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.jsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.ts
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.tsx
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.svelte
  ✘ /home/server/projects/svelte/ant-design-svelte/demo/antd/Typography.svx
```

**Comment by tommywalkie** [comment]
Could reproduce the issue on an Alpine Linux Docker image and looks like folder mounting is a known issue with Snowpack (https://github.com/snowpackjs/snowpack/issues/1278) leading to different results between Windows and Unix. Usually we would mount the _to-be-bundled_ folders in `snowpack.config.js`, in the `mount` field. 
Except some path like `/_dist_/components/Grid` seems to be treated as `http://localhost:8080/_dist_/components/Grid/index.js` on Windows/Firefox DevTools while in Unix it does look for something like `/home/ant-design-svelte/demo/_dist_/components/Grid.js`.

For now, I think I'm gonna switch to a Svelte/Rollup based SPA which might be a better and stable alternative.

**Comment by high1** [comment]
Hey, do you maybe have a repo where this issue could be simply reproducible? I've started to do some minor contributions to Snowpack, and this is something that I would like to eventually refactor completely.

**Comment by tommywalkie** [comment]
@high1 The issue is OS-specific, so the issue can be reproduced either using a (dockerized or physical) MacOS/Linux environment, we could also use Github Actions Ubuntu machine.

**Comment by tommywalkie** [comment]
@high1 Just set up a plain simple workflow so you access [the issue logs here](https://github.com/tommywalkie/ant-design-svelte/actions/runs/411422669).

**Comment by high1** [comment]
My plan is to run it on Windows and WSL 2, so I can get to the bottom of this.

**Comment by dishuostec** [comment]
Have you tried to rename `src/components/grid` to `src/components/Grid`? It seems because of the wrong capitalization.

**Comment by tommywalkie** [comment]
@dishuostec Oh that must be it. On my machine I renamed the folder but I suspect Git didn't take it into account. Gotta look into it.

**Comment by tommywalkie** [comment]
Well, the build now works [#415174816](https://github.com/tommywalkie/ant-design-svelte/actions/runs/415174816).
One remaining issue with the Vercel production build is about the `demo/antd/Typography.tsx` file.

**Comment by tommywalkie** [comment]
Just waiting for CI to complete and then I think I can properly close the issue

**Comment by tommywalkie** [comment]
Now it works! Thanks @dishuostec!
https://ant-design-svelte.tommywalkie.vercel.app
