### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Acidic9** [tommywalkie/ant-design-svelte#3]
I've been keeping an eye on this project because I think it can be very valuable to the Svelte community.

Recently I noticed you added in the project about text: `"[STALE]"`.
What are your plans for this project? Do you intend to continue development on it?

Thanks for all the hard work so far!

**Comment by tommywalkie** [comment]
Hi, thanks for reaching me @Acidic9.

In short, I just went a bit busy with pro matters and 2020's holidays, so I couldn't work on any of my OSS projects, hence the temporary `[STALE]` label. I **should** get back on it next week.

I can tell you I'm working with its React counterpart at work and I'm definitely looking forward to a Svelte alternative 😄

**Comment by Acidic9** [comment]
This is awesome, thank you so much. I am looking to use this in production soon, and I'd be willing to spend some time on it to help out. I'd just need to look into what approach you're taking with this.

And I don't mean to push you or anything, you have nothing to apologise for!
